LISTA_REGLAS = [
    "Al inicio del juego,",
    " el jugador estará posicionado en el centro",
    "de un tablero de 31 casilleros",
    "El mismo deberá responder preguntas",
    "Si responde bien, avanza un casillero,",
    "Si responde mal, retrocede un casillero.",
    "",
    "IMPORTANTE:",
    "- Tendrán 30 segundos para responder.",
    "- Si se acaba el tiempo, se dará como incorrecta.",
    "- Los casilleros hacia la DERECHA tienen escaleras",
    "  pueden avanzar si caen en ellos.",
    "- Los casilleros hacia la IZQUIERDA tienen serpientes",
    "  debe retroceder si caen en ellos.",
    "- Si el jugador llega a la posicion 30, gana el juego.",
    "- Si el jugador llega a la posicion 0, pierde el juego.",
    "- Si se acaban las preguntas, se termina el juego.",
]
